/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import Database.DatabaseConnection;
import Home_page.Home;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Abhishek Sharma
 */
public class Manage_Staff extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Staff
     */
    public Manage_Staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnStaffRecord = new javax.swing.JButton();
        txtSearchStaffID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtExperience = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAcademic_Q = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDOJ = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtGender = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        txtFatherName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtContectNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Staff", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff Id");

        btnSearch.setBackground(new java.awt.Color(0, 102, 102));
        btnSearch.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnStaffRecord.setBackground(new java.awt.Color(0, 102, 102));
        btnStaffRecord.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnStaffRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnStaffRecord.setText("Staff' s Record");
        btnStaffRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(txtSearchStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnStaffRecord)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStaffRecord)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Staff");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Experience");

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Academic qualification");

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Designation");

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Salary");

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date of joining");

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Staff's id :");

        txtDOJ.setDateFormatString("dd, MM, yyyy");
        txtDOJ.setPreferredSize(new java.awt.Dimension(70, 17));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtAcademic_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtDOJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAcademic_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add ");
        btnAdd.setAlignmentX(0.5F);
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        btnAdd.setBorderPainted(false);
        btnAdd.setMargin(new java.awt.Insets(0, 15, 0, 15));
        btnAdd.setPreferredSize(new java.awt.Dimension(77, 19));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setAlignmentX(0.5F);
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        btnUpdate.setBorderPainted(false);
        btnUpdate.setMargin(new java.awt.Insets(0, 15, 0, 15));
        btnUpdate.setPreferredSize(new java.awt.Dimension(77, 19));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setAlignmentX(0.5F);
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        btnDelete.setBorderPainted(false);
        btnDelete.setMargin(new java.awt.Insets(0, 15, 0, 15));
        btnDelete.setPreferredSize(new java.awt.Dimension(77, 19));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setAlignmentX(0.5F);
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        btnClear.setBorderPainted(false);
        btnClear.setMargin(new java.awt.Insets(0, 15, 0, 15));
        btnClear.setPreferredSize(new java.awt.Dimension(77, 19));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setAlignmentX(0.5F);
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        btnBack.setBorderPainted(false);
        btnBack.setMargin(new java.awt.Insets(0, 15, 0, 15));
        btnBack.setPreferredSize(new java.awt.Dimension(77, 19));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setMinimumSize(new java.awt.Dimension(780, 325));
        jPanel3.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First name");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("last name");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of birth");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");

        txtFirstName.setToolTipText("Name");

        txtDate.setDateFormatString("dd, MM, yyyy");
        txtDate.setPreferredSize(new java.awt.Dimension(70, 17));

        txtGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Father's name");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mother's name");

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");

        txtAddress.setColumns(15);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contect no.");

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(txtContectNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContectNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String t1 = txtSearchStaffID.getText().trim();
        if (t1.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter a student ID before searching.");
            return;
        }
        try {
            int StaffID = Integer.parseInt(t1);          
            Connection conn = DatabaseConnection.getConnection();
            if (conn == null) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error establishing database connection.");
                return;
            }

            PreparedStatement pstmt = null;
            ResultSet rs = null;
            try {
                pstmt = conn.prepareStatement("SELECT * FROM Staff WHERE Staff_ID = ?");
                pstmt.setInt(1, StaffID);
                rs = pstmt.executeQuery();
                //check if student exists or not 
               if (rs.next()) {
                    // Student exists
                    javax.swing.JOptionPane.showMessageDialog(null, "Staff exists");

                    // Retrieve and set values for each field
                    txtStaffID.setText(String.valueOf(rs.getInt("Staff_ID")));
                    txtFirstName.setText(rs.getString("FirstName"));
                    txtLastName.setText(rs.getString("LastName"));
                    txtDate.setDate(rs.getDate("DOB"));
                    txtGender.setSelectedItem(rs.getString("Gender"));
                    txtFatherName.setText(rs.getString("Father_Name"));                    
                    txtMotherName.setText(rs.getString("Mother_Name"));                    
                    txtAddress.setText(rs.getString("Address"));
                    txtContectNo.setText(rs.getString("Contact_no"));
                    txtEmail.setText(rs.getString("Email"));
                    txtDOJ.setDate(rs.getDate("DOJ"));
                    txtDesignation.setText(rs.getString("Designation"));
                    txtSalary.setText(String.valueOf(rs.getDouble("Salary")));
                    txtAcademic_Q.setText(rs.getString("Academic_Q"));
                    txtExperience.setText(String.valueOf(rs.getInt("Experience")));
                    
                   
                    

                    javax.swing.JOptionPane.showMessageDialog(null, "all components working successfully");
                } else {
                    // Student does not exist
                    javax.swing.JOptionPane.showMessageDialog(null, "Student does not exist");
                }
                
            } catch (SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error executing query: " + e.getMessage());
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (pstmt != null) {
                        pstmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Error closing resources: " + e.getMessage());
                }
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Invalid student ID format. Please enter a valid integer.");
        }

      
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnStaffRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffRecordActionPerformed
        // TODO add your handling code here:
        Staff_record st = new Staff_record();
        st.setVisible(true);
        st.pack();
        st.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnStaffRecordActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        // Check if Staff ID is empty
        if (txtStaffID.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Staff ID");
            txtStaffID.requestFocus();
            return;
        }

        // Check if Staff ID already exists in the database
        try {
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pstmt;
            String query = "SELECT * FROM Staff WHERE Staff_ID = ?";
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, Integer.parseInt(txtStaffID.getText()));
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Staff ID already exists. Please choose a different ID.");
                txtStaffID.requestFocus();
                return;
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error checking Staff ID: " + e.getMessage());
            return;
        }

        // Check if First Name is empty
        if (txtFirstName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the First Name");
            txtFirstName.requestFocus();
            return;
        }

        // Check if Last Name is empty
        if (txtLastName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Last Name");
            txtLastName.requestFocus();
            return;
        }

        // Check if DOB is empty
        if (txtDate.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the Date of Birth");
            txtDate.requestFocus();
            return;
        }

        // Check if Gender is empty
        if (txtGender.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the Gender");
            txtGender.requestFocus();
            return;
        }

        // Check if Father Name is empty
        if (txtFatherName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Father's Name");
            txtFatherName.requestFocus();
            return;
        }

        // Check if Mother Name is empty
        if (txtMotherName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Mother's Name");
            txtMotherName.requestFocus();
            return;
        }

        // Check if Address is empty
        if (txtAddress.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Address");
            txtAddress.requestFocus();
            return;
        }

        // Check if Contact No is empty, has exactly 10 digits, and contains only digits
        if (txtContectNo.getText().trim().isEmpty() || txtContectNo.getText().trim().length() != 10 || !txtContectNo.getText().trim().matches("\\d+")) {
            if (txtContectNo.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Contact No");
            } else if (txtContectNo.getText().trim().length() != 10) {
                javax.swing.JOptionPane.showMessageDialog(null, "Contact No must have exactly 10 digits");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Contact No must contain only digits");
            }
            txtContectNo.requestFocus();
            return;
        }

        // Check if Email is empty
        if (txtEmail.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Email");
            txtEmail.requestFocus();
            return;
        }

        // Check if DOJ is empty
        if (txtDOJ.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the Date of Joining");
            txtDOJ.requestFocus();
            return;
        }

        // Check if Designation is empty
        if (txtDesignation.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Designation");
            txtDesignation.requestFocus();
            return;
        }

        // Check if Salary is empty
        if (txtSalary.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Salary");
            txtSalary.requestFocus();
            return;
        }

        // Check if Academic Qualification is empty
        if (txtAcademic_Q.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Academic Qualification");
            txtAcademic_Q.requestFocus();
            return;
        }

        // Check if Experience is empty
        if (txtExperience.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Experience");
            txtExperience.requestFocus();
            return;
        }
        
        // Get values from text fields
        int StaffId = Integer.parseInt(txtStaffID.getText());
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        Date sqlDate = new Date(txtDate.getDate().getTime());
        String gender = (String) txtGender.getSelectedItem();
        String fatherName = txtFatherName.getText();
        String motherName = txtMotherName.getText();
        String address = txtAddress.getText();
        String contactNo = txtContectNo.getText();
        String email = txtEmail.getText();
        Date doj = new Date(txtDOJ.getDate().getTime());
        String designation = txtDesignation.getText();
        double salary = Double.parseDouble(txtSalary.getText());
        String academicQ = txtAcademic_Q.getText();
        int experience = Integer.parseInt(txtExperience.getText());       

        // Insert into the database
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pstmt;
        String query = "INSERT INTO Staff (Staff_ID, FirstName, LastName, DOB, Gender, Father_Name, Mother_Name, Address, Contact_no, Email, DOJ, Designation, Salary, Academic_Q, Experience) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, StaffId);
            pstmt.setString(2, firstName);
            pstmt.setString(3, lastName);
            pstmt.setDate(4, sqlDate);
            pstmt.setString(5, gender);
            pstmt.setString(6, fatherName);
            pstmt.setString(7, motherName);
            pstmt.setString(8, address);
            pstmt.setString(9, contactNo);
            pstmt.setString(10, email);
            pstmt.setDate(11, doj);
            pstmt.setString(12, designation);
            pstmt.setDouble(13, salary);
            pstmt.setString(14, academicQ);
            pstmt.setInt(15, experience);          
            
            // Execute the query
            pstmt.executeUpdate();

            // Show a success message
            javax.swing.JOptionPane.showMessageDialog(null, "Staff added successfully!");
        } catch (SQLException e) {
            // Handle any SQL exceptions
            javax.swing.JOptionPane.showMessageDialog(null, "Error adding Staff: " + e.getMessage());
        }
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // Check if Staff ID is empty
        if (txtSearchStaffID.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Staff ID to update");
            txtSearchStaffID.requestFocus();
            return;
        }

        // Check if Staff ID exists in the database
        try {
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pstmt;
            String query = "SELECT * FROM Staff WHERE Staff_ID = ?";
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, Integer.parseInt(txtSearchStaffID.getText()));
            ResultSet rs = pstmt.executeQuery();
            if (!rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Staff ID does not exist. Please choose a different ID.");
                txtSearchStaffID.requestFocus();
                return;
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error checking Staff ID: " + e.getMessage());
            return;
        }

        // Check if First Name is empty
        if (txtFirstName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the First Name");
            txtFirstName.requestFocus();
            return;
        }

        // Check if Last Name is empty
        if (txtLastName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Last Name");
            txtLastName.requestFocus();
            return;
        }

        // Check if DOB is empty
        if (txtDate.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the Date of Birth");
            txtDate.requestFocus();
            return;
        }

        // Check if Gender is empty
        if (txtGender.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the Gender");
            txtGender.requestFocus();
            return;
        }

        // Check if Father Name is empty
        if (txtFatherName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Father's Name");
            txtFatherName.requestFocus();
            return;
        }

        // Check if Mother Name is empty
        if (txtMotherName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Mother's Name");
            txtMotherName.requestFocus();
            return;
        }

        // Check if Address is empty
        if (txtAddress.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Address");
            txtAddress.requestFocus();
            return;
        }

        // Check if Contact No is empty, has exactly 10 digits, and contains only digits
        if (txtContectNo.getText().trim().isEmpty() || txtContectNo.getText().trim().length() != 10 || !txtContectNo.getText().trim().matches("\\d+")) {
            if (txtContectNo.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Contact No");
            } else if (txtContectNo.getText().trim().length() != 10) {
                javax.swing.JOptionPane.showMessageDialog(null, "Contact No must have exactly 10 digits");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Contact No must contain only digits");
            }
            txtContectNo.requestFocus();
            return;
        }

        // Check if Email is empty
        if (txtEmail.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Email");
            txtEmail.requestFocus();
            return;
        }

        // Check if DOJ is empty
        if (txtDOJ.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the Date of Joining");
            txtDOJ.requestFocus();
            return;
        }

        // Check if Designation is empty
        if (txtDesignation.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Designation");
            txtDesignation.requestFocus();
            return;
        }

        // Check if Salary is empty
        if (txtSalary.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Salary");
            txtSalary.requestFocus();
            return;
        }

        // Check if Academic Qualification is empty
        if (txtAcademic_Q.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Academic Qualification");
            txtAcademic_Q.requestFocus();
            return;
        }

        // Check if Experience is empty
        if (txtExperience.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Experience");
            txtExperience.requestFocus();
            return;
        }
       

        // Update the Staff's information in the database
        try {
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pstmt;
            String query = "UPDATE Staff SET FirstName = ?, LastName = ?, DOB = ?, Gender = ?, Father_Name = ?, Mother_Name = ?, Address = ?, Contact_No = ?, Email = ?, DOJ = ?, Designation = ?, Salary = ?, Academic_Q = ?, Experience = ? WHERE Staff_ID = ?";
            pstmt = conn.prepareStatement(query);
            pstmt.setString(1, txtFirstName.getText());
            pstmt.setString(2, txtLastName.getText());
            pstmt.setDate(3, new Date(txtDate.getDate().getTime()));
            pstmt.setString(4, txtGender.getSelectedItem().toString());
            pstmt.setString(5, txtFatherName.getText());
            pstmt.setString(6, txtMotherName.getText());
            pstmt.setString(7, txtAddress.getText());
            pstmt.setString(8, txtContectNo.getText());
            pstmt.setString(9, txtEmail.getText());
            pstmt.setDate(10, new Date(txtDOJ.getDate().getTime()));
            pstmt.setString(11, txtDesignation.getText());
            pstmt.setString(12, txtSalary.getText());
            pstmt.setString(13, txtAcademic_Q.getText());
            pstmt.setString(14, txtExperience.getText());            
            pstmt.setInt(15, Integer.parseInt(txtSearchStaffID.getText()));
            pstmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(null, "Staff's information updated successfully");
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error updating Staff's information: " + e.getMessage());
        }
        btnClearActionPerformed(null);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         // Check if Staff ID is empty
        if (txtSearchStaffID.getText().trim().isEmpty ()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Staff ID to delete");
            txtSearchStaffID.requestFocus();
            return;
        }

        // Check if Staff ID exists in the database
        try {
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pstmt;
            String query = "SELECT * FROM Professor WHERE Professor_ID = ?";
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, Integer.parseInt(txtSearchStaffID.getText()));
            ResultSet rs = pstmt.executeQuery();
            if (!rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Staff ID does not exist. Please choose a different ID.");
                txtSearchStaffID.requestFocus();
                return;
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error checking Staff ID: " + e.getMessage());
            return;
        }

        // Confirm deletion
        int confirm = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Staff?", "Delete Staff", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Delete the Staff's information from the database
            try {
                Connection conn = DatabaseConnection.getConnection();
                PreparedStatement pstmt;
                String query = "DELETE FROM Staff WHERE Staff_ID = ?";
                pstmt = conn.prepareStatement(query);
                pstmt.setInt(1, Integer.parseInt(txtSearchStaffID.getText()));
                pstmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(null, "Staff deleted successfully");
            } catch (SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error deleting Staff: " + e.getMessage());
            }
        }
        btnClearActionPerformed(null);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtStaffID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtDate.setDate(null);
        txtGender.setSelectedItem(null);
        txtFatherName.setText("");
        txtMotherName.setText("");
        txtAddress.setText("");
        txtContectNo.setText("");
        txtEmail.setText("");
        txtDOJ.setDate(null);
        txtDesignation.setText("");
        txtSalary.setText("");
        txtAcademic_Q.setText("");
        txtExperience.setText("");
        
        txtSearchStaffID.requestFocusInWindow();
        txtSearchStaffID.selectAll();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnStaffRecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAcademic_Q;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContectNo;
    private com.toedter.calendar.JDateChooser txtDOJ;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JComboBox txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearchStaffID;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
